TINY_WAIT = 1
SMALL_WAIT = 3
MEDIUM_WAIT = 5
BIG_WAIT = 10
SECURITY_WAIT = 15
BATTLE_FINISH_DETECT = 12
BATTLE_NONE_DETECT_TIME = 90

# 调试等级
# 0 正常运行
# 1 输出函数调用过程
# 2 输出所有中间参数
DEBUG_LEVEL = 0

BATTLE_END_SIGNAL_MAX_EXECUTE_TIME = 15

# 拖动偏移
# 用于左右拖动的偏移，也就是偏移初始坐标点
FLAGS_SWIPE_BIAS_TO_LEFT = ((10, 10), (10, 10))
FLAGS_SWIPE_BIAS_TO_RIGHT = ((10, 10), (10, 10))
