SMALL_WAIT = 3
MEDIUM_WAIT = 5
BIG_WAIT = 10
SECURITY_WAIT = 15
BATTLE_FINISH_DETECT = 30

# 正方形偏移
FLAGS_CLICK_BIAS_TINY = (3, 3)
FLAGS_CLICK_BIAS_SMALL = (5, 5)
FLAGS_CLICK_BIAS_MEDIUM = (10, 10)
FLAGS_CLICK_BIAS_BIG = (15, 15)
FLAGS_CLICK_BIAS_HUGE = (30, 30)

# 拖动偏移
# 用于左右拖动的偏移，也就是偏移初始坐标点
FLAGS_SWIPE_BIAS_TO_LEFT = ((5, 300), (1, 1))
FLAGS_SWIPE_BIAS_TO_RIGHT = ((5, 300), (1, 1))
